import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { getGraphQLData } from '../lib/topics';


export async function getStaticProps({topicString}) {
  const allTopicsData = await getGraphQLData(topicString)
  console.log('allTopicsData getProps', allTopicsData)

  return {
    props: {
      allTopicsData
    }
  }
}

export default function Home({ allTopicsData }) {
  let topicString = 'react';
  let stargazers = allTopicsData.data.topic.stargazerCount;
  let relatedTopics = allTopicsData.data.topic.relatedTopics;
  console.log('Home allTopicsData', allTopicsData);
  console.log(allTopicsData.data.topic.stargazerCount);
  console.log('relatedTopics', relatedTopics)

  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub Topics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Github Topics
        </h1>
          <p className={styles.description}>
          Find GitHub Topics related to {' '}
          <Link href="/">
            <a>React</a>
          </Link>
          </p>
          <h2>{topicString}</h2>
          <span>{`stargazers: ${stargazers}`}</span> 
        <h2>Related Topics</h2>
          <ul>
            {/* {relatedTopics.map((topic, index) => {
              console.log(topic.name);
              <li key={index}>{topic.name}</li>
            }
            )} */}
          {relatedTopics.map((topic, index) => (
            <li key={index}>
              <Link href={`/topics/${topic.name}`}>
                <a>{topic.name}</a>
              </Link>
            </li>
          ))}
          </ul>
      </main>

      <footer className={styles.footer}>]
        GitHub Topics | 2021
      </footer>
    </div>
  )
}